### ISSUE TITLE
Vitalparameter Maintenance

### ISSUE THREAD

**Issue by ylboerner** [gematik/spec-ISiK-Vitalparameter-und-Koerpermasse#130]
- [x] SUSHI Version erhöhen
- [ ] Validierungsfehler prüfen
- [ ] Use slice name instead of numeric index access
- [ ] Fix eventual errors

Vergleiche ggf. mit Terminplanung : https://github.com/gematik/spec-ISiK-Terminplanung/pull/128

```[tasklist]
### Tasks
- [ ] PTDATA-673
```
